package com.trading.journal.currenciesDB;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Currencies {

    public static List<String> forexCurrencies = new ArrayList<>(Arrays.asList(
                    "EURUSD - Euro US Dollar",
                    "USDJPY - US Dollar Japanese Yen",
                    "GBPUSD - British Pound US Dollar",
                    "USDCHF - US Dollar Swiss Franc",
                    "AUDUSD - Australian Dollar US Dollar",
                    "USDCAD - US Dollar Canadian Dollar",
                    "NZDUSD - New Zealand Dollar US Dollar",
                    "EURGBP - Euro British Pound",
                    "EURJPY - Euro Japanese Yen",
                    "GBPJPY - British Pound Japanese Yen",
                    "AUDJPY - Australian Dollar Japanese Yen",
                    "EURCHF - Euro Swiss Franc",
                    "USDHKD - US Dollar Hong Kong Dollar",
                    "USDSGD - US Dollar Singapore Dollar",
                    "USDTHB - US Dollar Thai Baht",
                    "USDMXN - US Dollar Mexican Peso",
                    "USDSEK - US Dollar Swedish Krona",
                    "USDNOK - US Dollar Norwegian Krone",
                    "USDDKK - US Dollar Danish Krone",
                    "USDTRY - US Dollar Turkish Lira",
                    "USDZAR - US Dollar South African Rand",
                    "USDINR - US Dollar Indian Rupee",
                    "USDBRL - US Dollar Brazilian Real",
                    "EURCAD - Euro Canadian Dollar",
                    "EURAUD - Euro Australian Dollar",
                    "EURNZD - Euro New Zealand Dollar",
                    "EURSEK - Euro Swedish Krona",
                    "EURNOK - Euro Norwegian Krone",
                    "EURDKK - Euro Danish Krone",
                    "EURTRY - Euro Turkish Lira",
                    "EURZAR - Euro South African Rand",
                    "GBPAUD - British Pound Australian Dollar",
                    "GBPCAD - British Pound Canadian Dollar",
                    "GBPCHF - British Pound Swiss Franc",
                    "GBPNZD - British Pound New Zealand Dollar",
                    "GBPSEK - British Pound Swedish Krona",
                    "GBPNOK - British Pound Norwegian Krone",
                    "GBPDKK - British Pound Danish Krone",
                    "GBPTRY - British Pound Turkish Lira",
                    "GBPZAR - British Pound South African Rand",
                    "AUDNZD - Australian Dollar New Zealand Dollar",
                    "AUDCHF - Australian Dollar Swiss Franc",
                    "AUDCAD - Australian Dollar Canadian Dollar",
                    "AUDSGD - Australian Dollar Singapore Dollar",
                    "NZDJPY - New Zealand Dollar Japanese Yen",
                    "NZDCHF - New Zealand Dollar Swiss Franc",
                    "NZDCAD - New Zealand Dollar Canadian Dollar",
                    "CADJPY - Canadian Dollar Japanese Yen",
                    "CADCHF - Canadian Dollar Swiss Franc",
                    "CHFJPY - Swiss Franc Japanese Yen",
                    "USDCNH - US Dollar Chinese Yuan",
                    "USDPLN - US Dollar Polish Zloty",
                    "USDRUB - US Dollar Russian Ruble",
                    "USDIDR - US Dollar Indonesian Rupiah",
                    "USDPHP - US Dollar Philippine Peso",
                    "USDARS - US Dollar Argentine Peso",
                    "USDCLP - US Dollar Chilean Peso",
                    "USDCOP - US Dollar Colombian Peso",
                    "USDPEN - US Dollar Peruvian Sol",
                    "USDCNY - US Dollar Chinese Yuan Renminbi",
                    "USDKRW - US Dollar South Korean Won",
                    "USDTWD - US Dollar New Taiwan Dollar",
                    "USDMYR - US Dollar Malaysian Ringgit",
                    "USDSGD - US Dollar Singapore Dollar",
                    "USDILS - US Dollar Israeli Shekel",
                    "USDHUF - US Dollar Hungarian Forint",
                    "USDCZK - US Dollar Czech Koruna",
                    "USDPLN - US Dollar Polish Zloty",
                    "USDHRK - US Dollar Croatian Kuna",
                    "USDRON - US Dollar Romanian Leu",
                    "USDUAH - US Dollar Ukrainian Hryvnia",
                    "EURPLN - Euro Polish Zloty",
                    "EURRUB - Euro Russian Ruble",
                    "EURCZK - Euro Czech Koruna",
                    "EURHUF - Euro Hungarian Forint",
                    "GBPZAR - British Pound South African Rand",
                    "GBPSGD - British Pound Singapore Dollar",
                    "GBPPLN - British Pound Polish Zloty",
                    "GBPHKD - British Pound Hong Kong Dollar",
                    "AUDHKD - Australian Dollar Hong Kong Dollar",
                    "AUDCNY - Australian Dollar Chinese Yuan",
                    "AUDTHB - Australian Dollar Thai Baht",
                    "NZDHKD - New Zealand Dollar Hong Kong Dollar",
                    "NZDCNY - New Zealand Dollar Chinese Yuan",
                    "NZDTHB - New Zealand Dollar Thai Baht",
                    "CADHKD - Canadian Dollar Hong Kong Dollar",
                    "CADCNY - Canadian Dollar Chinese Yuan",
                    "CHFCNH - Swiss Franc Chinese Yuan Renminbi",
                    "CHFHKD - Swiss Franc Hong Kong Dollar",
                    "EURCNY - Euro Chinese Yuan Renminbi",
                    "EURHKD - Euro Hong Kong Dollar",
                    "EURTHB - Euro Thai Baht",
                    "GBPCNY - British Pound Chinese Yuan",
                    "GBPHUF - British Pound Hungarian Forint",
                    "GBPSEK - British Pound Swedish Krona",
                    "AUDNOK - Australian Dollar Norwegian Krone",
                    "AUDSEK - Australian Dollar Swedish Krona",
                    "CADNOK - Canadian Dollar Norwegian Krone",
                    "CHFNOK - Swiss Franc Norwegian Krone"
            ));
}
